<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Chroma</RootNamespace>
    <AssemblyName>Chroma</AssemblyName>
    <ApplicationIcon />
    <Company>M-Tre Consulting</Company>
    <Product>Chroma</Product>
    <Copyright>© 2026 M-Tre Consulting. All rights reserved.</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="ic_launcher.png" />
    <Resource Include="mtre-logo.png" />
  </ItemGroup>

</Project>
